openapi: '3.0.2'
info:
  title: 掲示板 REST API
  version: '1.0'
servers:
  - url: http://localhost:8080/v1
    description: ローカル環境
paths:
  /threads:
    get:
      tags:
        - billboard
      operationId: threadList
      description: スレッドの一覧を取得する。
      responses:
        200: 
          description: スレッドの一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ThreadList'
  /thread/{threadId}:
    parameters:
      - name: threadId
        in: path
        description: スレッドID
        required: true
        schema:
          type: integer
          format: int32
    get:
      tags:
        - billboard
      description: 掲示板を参照する
      operationId: showThread
      responses:
        200:
          description: 投稿内容の一覧を投稿日時に昇順で取得する
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Thread'
    post:
      tags:
        - billboard
      operationId: writeComment
      description: 掲示板にコメントを追加する
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        201:
          description: 投稿成功時にはサーバサイドで必要な情報を付与したコメント内容を返却する。
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Comment'
  
  /comment/like/{threadId}/{seq}:
    put:
      tags:
        - billboard
      description: コメントへのいいねを付与する
      parameters:
        - name: threadId
          in: path
          description: スレッドID
          required: true
          schema:
            type: integer
            format: int32
        - name: seq
          in: path
          description: コメントSEQ
          required: true
          schema:
            type: integer
            format: int32
      responses:
        201: 
          description: いいねのカウントアップに成功
components:
  schemas:
    ThreadList:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int32
          description: スレッドID
        title:
          type: string
          description: スレッドタイトル
    Thread:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int32
          description: スレッドID
        title:
          type: string
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
    Comment:
      type: object
      required:
        - post_name
        - comment
      properties:
        seq:
          type: integer
          maxLength: 1000
        post_name:
          type: string
          maxLength: 20
          description: 投稿者名
        post_date:
          type: string
          format: date-time
          description: 投稿日時
        comment:
          type: string
          description: 投稿内容
          maxLength: 300
        good_count:
          type: integer
          format: int32
          description: いいね！




